### ISSUE TITLE
backstories 주석 질문

### ISSUE THREAD

**Issue by rodpold** [Ludeon/RimWorld-Korean#145]
안녕하세요 ㅎ

코드 clone 받고 조금 확인해 보고 있는데 backstories 부분에 3분에 2 정도는 주석 처리가 되어 있더라고요 ㅎ

이게 원래 그런건지, 아니면 주석을 풀고 번역을 해야 되는 것인가요?

**Comment by urty5656** [comment]
풀고 해주세요. 내용이 같으면(번역이 안돼있으면) 오류가 떠서요.
