### ISSUE TITLE
backstories 번역 질문

### ISSUE THREAD

**Issue by AlphaLeaf** [Ludeon/RimWorld-Korean#147]
안녕하세요. backstories 부분을 번역하는데 몇가지 질문드리고 싶습니다.
1.HE,HIS,HECAP등이 등장하는데, 이것들은 무조건 순서랑 갯수가 원본이랑 똑같이 되어야하나요? 아니면 번역을 깔끔하게 하기 위해 순서를 바꾸거나 삭제,추가가 가능한 건가요? 일단은 최대한 원본이랑 순서, 갯수 똑같게하여 하나 PR하였습니다.
2.번화계, 동굴계같은 게임 세계관상 용어도 나오는 듯 한데 어떤 단어를 이렇게 번역하게 되는지 관련 정보를 알려주셨으면 좋겠어요!

**Comment by urty5656** [comment]
대문자 대명사들은 게임 내에서 그/그녀/그는/그녀는/그의/그녀의 등등으로 대체돼서 나오니까 적당히 바꿔주세요. 번역본 Keyed/Grammar.xml 참고해주세요. HE(그는/그녀는)랑 HECAP(그/그녀)이 서로 다른 것도 주의해주시구요.

~~계는 보통 행성 타입을 가리킵니다. [여기](https://docs.google.com/document/d/1pIZyKif0bFbBWten4drrm7kfSSfvBoJPgG9-ywfN8j8/pub)서 보실 수 있구요, 번역본은 [여기](http://blog.naver.com/rooki12k/220293040885) 참고해주세요. 저는

- 동물
- 부족
- 중세
- 산업
- 변경계 (Rimworld)
- 중간
- 밀집
- 번화계 (Glitterworld)
- 초월

으로 하고 있어요. 번화계/변경계는 오래 썼는데, 나머지는 지금까진 쓸 일도 없었고 '동굴계' 같은건 프라이머에도 나와있지 않으니까 의견 주시면 감사합니당.
