### ISSUE TITLE
Backstories 번역 참고

### ISSUE THREAD

**Issue by kisu320** [Ludeon/RimWorld-Korean#164]
# 용어 관련
주로 쓰이는 용어를 통일하려고 합니다.
셰계관 참고글: http://blog.naver.com/rooki12k/220293040885

## Medieval - 중세 / Medieval worlds - 중세계
Medieval만 쓰인 경우와 Medieval worlds로 쓰인 경우를 구분해주세요.

## Urbworld - 도시계
밀집계/조밀계/도시계/도심계 여러가지로 혼용됐으나 앞으로 **도시계**로 통일했으면 합니다.

## Homeworld - 고향
이전에 번역한 분이 모행성/모성으로 번역했던데, 모행성은 위성이 공전하고 있는 행성을 뜻하는 말로 오역으로 생각됩니다.
 **고향**으로 통일했으면 합니다. 다른 좋은 제안이 있으면 해주시기 바랍니다.

## Vatgrown - 인공배양
**탱크 출신**이라는 요상한... 오역이 있었습니다.
Vatgrown은 인공적으로 배양되어 출생된 사람들을 일컫는 말입니다.
**인공배양**으로 통일했으면 합니다. 다른 좋은 제안이 있으면 해주시기 바랍니다.

## System - 성계
문맥상 제도, 체계, 시스템이 아닌 Solar System(태양계)의 System과 같은 뜻으로 쓰이는 경우가 있습니다.
**성계**로 통일했으면 합니다. 다른 좋은 제안이 있으면 해주시기 바랍니다.

**Comment by kisu320** [comment]
# 대명사 관련
## NAME
림의 이름입니다. 뒤에 조사를 붙일 경우 "(은)는"형식으로 해주세요.

가끔 **NAME**이 아예 들어가지 않은 문장이 있습니다.
제 추측인데 림월드에서 번역 파일을 제공한 게 아니라 이전에 작업하신 분이 일일이 따오신 거 같습니다.
그래서 NAME 대신 림의 이름이 직접 들어가 있는 경우가 있습니다.

> 예시: Felix grew up in a large factory city on an industrial world.
> 변경: NAME grew up in a large factory city on an industrial world.

이런 경우 이름인 부분을 NAME으로 바꿔서 번역해야 합니다.

## 3인칭 대명사
- HE = 그/그녀
- HECAP = 그는/그녀는
- HIS, HISCAP = 그의/그녀의
- HIM ,HIMCAP = 그를/그녀를

한글 문장으로 번역할 때 자연스럽게 하려고 변경/추가/삭제해도 됩니다.
다만 한글로 직접 "그는"처럼 번역하면 안 됩니다.

> 한국어로 번역했을 때 뺀 경우가 자연스러울 경우 빼도 됩니다.
> HECAP는 HIS 삶에서 = 그는 그의 삶에서
> HECAP는 삶에서 = 그는 삶에서

> 변경의 경우
> 원문에 "HE(그는/그녀는)"를 "그가/그녀가"로 번역해야 할 때는 "HECAP가"로 변경해도 됩니다.

NAME과 마찬가지로 소문자로 들어가 있는 경우가 있습니다. 이 역시 바꿔서 번역해야 합니다.

> 예시: he saw friends injured and killed.
> 변경: HE saw friends injured and killed.

**Comment by urty5656** [comment]
# 용어
## 중세
배경 이야기에서 Medieval이 나온다면 중세계로 번역해도 괜찮다고 봐요. 현대문명과 중세문명이 공존하지 않으니 중세에서 왔다 = 중세계에서 왔다는 같은 뜻이니까요.

## 홈월드
SF인 점을 생각했을 때 모성도 괜찮다고 생각해요. 모행성은 뭐... 그리고 모성이 행성인지 항성인지는 문맥만으로 구분 가능하니까요.

# 대명사

## NAME
번역파일 림월드에서 제공하는거 맞아요... :disappointed: 
굳이 NAME으로 바꿀 필요 없습니다. 후원자 이름에 묶인 전용 배경이야기니까요. 물론 바꿔도 되니까 통일하고 싶으시면 하셔도 무방하구요.

## 3인칭
위와 동일합니다. 굳이 바꿀 필요 없이 그/그녀로 하셔도 됩니다. 통일하고 싶으시면 하셔도 상관은 없어요.

**Comment by kisu320** [comment]
Homeworld의 경우 모행성/모항성/모성은 명백한 오역이라고 생각됩니다.
세 단어는 행성-위성/항성-행성 간의 관계에서 쓰이는 단어이지... 행성(위성)-거주생명체 간의 관계에서 쓰이는 단어가 아닙니다.

**Comment by rodpold** [comment]
NAME의 경우엔 플레이 하는 게이머가 캐릭터의 이름을 임의로 변경했을 때 NAME 변수가 아니면 함께 변경되지 않는 경우가 발생할 수 있을 것 같습니다. ㅎ

**Comment by kisu320** [comment]
NAME에 후원자 이름이 들어갈 거란 건 미처 생각을 못 했네요.
바꾸는 게 사실 게임 내에서는 자연스럽지만, 후원자 이름을 빼는 것에 대해선 고민해봐야 할 것 같습니다.

3인칭 대명사는 한국어로 번역하셔도 됩니다. 제가 보일 때마다 변수로 수정해 통일하겠습니다.

**Comment by rodpold** [comment]
NAME은 고민해봤는데 후원자 이름이 들어간다 해도 게임의 디테일을 위해서는 NAME변수를 사용해야 한다고 봅니다.
후원자 이름이 들어간 캐릭터를 플레이어가 조종한다고 해도 플레이어는 게임 내에서 임의로 캐릭터의 이름을 변경할 수 있기 때문입니다. 
림월드에서는 캐릭터 이름을 변경하는 경우 배경 스토리에 포함된 이름 역시 함께 바뀌게끔 의도한 것 같더군요 ㅎ;
HECAP등도 어째서 변수로 했는지 고민해 봤는데 추후 캐릭터의 성별이 바뀐다거나 했을 때를 고려하여 변수로 두지 않았나 싶습니다.

**Comment by NyaamZ** [comment]
[PAWN_pronoun]가  
그녀는가 
같은 번역 오류 때문에 keyed\Grammar.xml의
    <Prohe>그는</Prohe>        그는->그
    <Proshe>그녀는</Proshe> 그녀는->그녀
로 고칩니다.

**Comment by rodpold** [comment]
많이 고생해 주시네요 감사합니다 ㅠㅠ 요새 일이 워낙 바빠서 손도 못 댔는데 이따가 시간이 되면 새 버전 적용 후 업데이트 해보겠습니다

2018년 9월 7일 (금) 오후 7:42, NyaamZ <notifications@github.com>님이 작성:

**Comment by MilSuUpZa** [comment]
15일 전에 도움 주는 사람들과 첨부터 끝까지 룰 팩과 Tale 부분을 제외하곤 전부 오역 및 오류 수정, 패치되며 사라진 것들 정리, 최적화 하였습니다. 양이 너무 많기에 일일이 수정이 아닌, 전체적으로 다시 코드를 뽑아 작업하였으며, 여기에 파일 교체를 통해 수정하였습니다.

아직 남아있는 사람이 있는 줄은 몰랐네요.

**Comment by NyaamZ** [comment]
풀 리퀘스트 컨펌 누가 해주시는지 아시나요? 제가 올린 리퀘스트 검토해서 반영해주시면 좋겠습니다.

**Comment by MilSuUpZa** [comment]
조력에 감사합니다. 지금 타이난과 약간의 마찰이 있어서 문제가 좀 있습니다. 타이난이 번역을 다 날려먹었거든요. 일단 상황을 지켜보고
있는 상태입니다.

2018년 10월 16일 (화) 오전 1:18, NyaamZ <notifications@github.com>님이 작성:

**Comment by NyaamZ** [comment]
타이난이 몇 개 날렸다 해도 제가 거의 다 채워넣어서 크게 상관은 없는데........

아무튼 빨리 해결되었으면 좋겠습니다.

**Comment by MilSuUpZa** [comment]
파일 어디에 올라셨어요?

2018년 10월 16일 (화) 오후 9:53, NyaamZ <notifications@github.com>님이 작성:

**Comment by NyaamZ** [comment]
Pull Request 입니다.

**Comment by MilSuUpZa** [comment]
와 스벌. 덕분에 살았습니다. 4개월간 노력이 물거품 되는 줄 알았는데.

2018년 10월 16일 (화) 오후 8:53, NyaamZ <notifications@github.com>님이 작성:

**Comment by MilSuUpZa** [comment]
혹시 choibom90127@gmail.com 으로 파일 보내주실 수 있을까요?

2018년 10월 16일 (화) 오후 9:03, NyaamZ <notifications@github.com>님이 작성:

**Comment by NyaamZ** [comment]
지금 보냅니다.

**Comment by MilSuUpZa** [comment]
번거롭게 해서 죄송합니다.

2018년 10월 16일 (화) 오후 9:54, NyaamZ <notifications@github.com>님이 작성:

**Comment by MyDickforYou** [comment]
여기 번역 게시판 맞나요? 개발자모드 활성화 번역하려하는데 어디서 하나요

**Comment by alattalatta** [comment]
@MyDickforYou 님, 개발자모드는 Def가 없으므로 번역할 수 없습니다.

**Comment by alattalatta** [comment]
오래된 이슈라 닫을까 했는데, 혹시 몰라서 기록용으로 계속 열어놓고 댓글만 잠가놓겠습니다. 추가로 필요하신 내용(게시판 등...)은 별도 이슈를 생성해주세요.

**Comment by alattalatta** [comment]
공지 추가했으므로 닫겠습니다.
