### ISSUE TITLE
Backstories에서 명사/대명사가 정해진 경우에 대해 외..

### ISSUE THREAD

**Issue by amrasanor** [Ludeon/RimWorld-Korean#196]
안녕하세요, 오늘 막 참여한 신입입니다. 특별히 관련 공지문이 보이지 않아 부득이하게 Issues에 질문을 하게 되었습니다. 혹시 Pull requests에 하는 것이 맞다면 즉시 그곳으로 옮기겠습니다.
다름이 아니라, Backstories 원문을 보니 가끔 대명사 he(AcademyStudent80, AceFighterPilot38, AdventuringChild56, BanishedSoldier76 등), she(AspiringPhysicist25, AspiringPopIdol61, Athlete23 등)가 직접 제시되거나 아예 이름이 있는 경우(ArtfulDodger87, Assassin16의 Robin, AwkwardNerd12의 Dave, BountyHunter22의 Mushinto 등)가 있었는데요.
번역본에서는 이중 일부는 원문 그대로 대명사와 이름을 살렸지만, 또 [PAWN]으로 처리한 것도 있었습니다. 이 경우에 관한 지침이 어떻게 되는지 여쭙고 싶습니다.

그리고 재번역 혹은 번역 수정에 관해서도 알고 싶습니다. 번역문을 보다 보니 부사관(non-commissioned officer)을 장교로(ArmySergeant1), 식물 재배를 잘함(green thumb)을 문자 그대로 '초록색으로 물든 자신의 손'으로 번역하는 등(AmateurBotanist14) 오역이 간혹 보이는데, 이에 관한 의견 개진이나 제안은 Pull request에서 하면 될까요?

**Comment by alattalatta** [comment]
이슈도 질문/제안 등을 올리는 곳이 맞으니 걱정 안하셔도 됩니다. 실제로 파일에 변경을 하셨으면 변경점을 들고 PR로 가시면 되고, 아직 진행을 하지 않으셨다면 이슈에 올리시면 되지 않을까요?

---

@MilSuUpZa 님, 저장소에 Watch를 걸어주세요. 감사합니다.

**Comment by alattalatta** [comment]
@amrasanor 님, 번역 자체에 관해서는 여기보다 디스코드쪽을 사용하고 계신 것 같으니 이쪽에 문의하시는게 좋을거같아요. https://discord.gg/6PyAxGU

**Comment by alattalatta** [comment]
공지 추가했으므로 닫겠습니다.
